spring.application.name=jobmatch-service
server.port=8088

spring.datasource.url=${JOBMATCH_DB_URL:jdbc:mysql://localhost:3306/jobmatchdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${JOBMATCH_DB_USERNAME:root}
spring.datasource.password=${JOBMATCH_DB_PASSWORD}
spring.datasource.driver-class-name=${JOBMATCH_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${JOBMATCH_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JOBMATCH_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
