spring.application.name=notification-service
server.port=8087

spring.datasource.url=${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3306/notificationdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${NOTIFICATION_DB_USERNAME:root}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD}
spring.datasource.driver-class-name=${NOTIFICATION_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${NOTIFICATION_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${NOTIFICATION_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
