sonar.projectKey=pratyushjadonn_ResumeAI
sonar.organization=pratyushjadonn

sonar.host.url=https://sonarcloud.io

sonar.sources=.

sonar.java.binaries=**/target/classes

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/node_modules/**
