spring.application.name=section-service
server.port=8083

spring.datasource.url=${SECTION_DB_URL:jdbc:mysql://localhost:3306/sectiondb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SECTION_DB_USERNAME:root}
spring.datasource.password=${SECTION_DB_PASSWORD}
spring.datasource.driver-class-name=${SECTION_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${SECTION_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SECTION_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
