spring.application.name=template-service
server.port=8084

spring.datasource.url=${TEMPLATE_DB_URL:jdbc:mysql://localhost:3306/templatedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${TEMPLATE_DB_USERNAME:root}
spring.datasource.password=${TEMPLATE_DB_PASSWORD}
spring.datasource.driver-class-name=${TEMPLATE_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${TEMPLATE_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${TEMPLATE_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
