spring.application.name=resume-service
server.port=8082

spring.datasource.url=${RESUME_DB_URL:jdbc:mysql://localhost:3306/resumedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${RESUME_DB_USERNAME:root}
spring.datasource.password=${RESUME_DB_PASSWORD}
spring.datasource.driver-class-name=${RESUME_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${RESUME_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${RESUME_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
